# Scenario 2: population + fertility alignment

model_args:
  alignPopulation: true
  alignFertility: false
  alignCohabitation: false
  alignInSchool: true
  alignEmployment: false
  alignRetirement: false
  alignDisability: false
  alignEducation: false
