# This file can be used to override defaults for multirun arguments.
# Arguments of the SimPathsMultiRun object overridden by the command-line

maxNumberOfRuns: 5
executeWithGui: false
randomSeed: 1821
startYear: 2011
endYear: 2023
popSize: 50000

# Arguments passed to the SimPathsModel
model_args:
#    maxAge: 130
#    fixTimeTrend: true
#    timeTrendStopsIn: 2017
#    fixRandomSeed: true
#    sIndexTimeWindow: 5
#    sIndexAlpha: 2
#    sIndexDelta: 0
#    savingRate: 0
#    initialisePotentialEarningsFromDatabase: true
#    useWeights: false
#    useSBAMMatching:
#    projectMortality: true
#    alignFertility: true
#    labourMarketCovid19On: false
#    projectFormalChildcare: true
#    donorPoolAveraging: true
#    alignEmployment: false
#    projectSocialCare: false
#    enableIntertemporalOptimisations: true
#    responsesToLowWageOffer: true
#    saveImperfectTaxDBMatches: false
#    useSavedBehaviour: false
#    readGrid: "laptop serial"
#    saveBehaviour: true
#    employmentOptionsOfPrincipalWorker: 3
#    employmentOptionsOfSecondaryWorker: 3
#    responsesToEducation: true
#    responsesToRetirement: false
#    responsesToHealth: true
#    responsesToDisability: false
#    minAgeForPoorHealth: 50
#    responsesToRegion: false

#    Macromodel arguments
#    mm_macroModel: ramsey   # off | ramsey | dsge | ramsey_dsge
#    mm_useMacroPathRecorder: true  # Record L/h paths in MacroPaths.csv without macro feedback (works with mm_macroModel: off)
#    mm_macroLogging: state   # off | state | verbose
#    mm_ramseyScenario: "ramsey_high_gA.csv" # <-- the trend model scenario file; baseline runs (assumption: no deviation from trend) should comment it out
#    mm_dsgeShockScenario: "energy_shock_20q.csv"   # <-- the scenario file; baseline runs (assumption: all shocks zero) should comment it out
#    mm_dsgeMaxStateDeviation: 10.0 # Allowed maximum % deviation from steady state for DSGE; linearization accuracy deteriorates
#                       # beyond this range, so the simulation will crash if any state variable exceeds ±mm_dsgeMaxStateDeviation.


# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
#    randomSeedInnov: false
#    intertemporalElasticityInnov: false
#    labourSupplyElasticityInnov: true

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0